package com.revature.entity;

public class AvatarCharacter {

    //unique id for each entity
    //this number will be different for every avatar character, that way we can uniquely identify them
    private int id;
    //these next variables are characteristics of any character in the Avatar universe
    private String name;
    private String nation;
    private boolean bender;


    //default constructor
    public AvatarCharacter() {

    }

    //fully parameterized constructor
    public AvatarCharacter(int id, String name, String nation, boolean bender) {
        this.id = id;
        this.name = name;
        this.nation = nation;
        this.bender = bender;
    }


    //a constructor that sets up everything except the id
    //Why is this important?
    //has to be unique
    //SQL generates these id's for us automatically to be unique
    //when we create an AvatarCharacter object, we don't want to specify an id because it will be generated by the database anyways
    public AvatarCharacter(String name, String nation, boolean bender) {
        this.name = name;
        this.nation = nation;
        this.bender = bender;
    }


    //getters and setters to allow us to access the private member variables
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNation() {
        return nation;
    }

    public void setNation(String nation) {
        this.nation = nation;
    }

    public boolean getBender() {
        return bender;
    }

    public void setBender(boolean bender) {
        this.bender = bender;
    }

    @Override
    public String toString() {
        return "Character\n" + " id: " + id +
                "\n name: " + name +
                "\n nation: " + nation +
                "\n bender: " + bender;
    }
}
